version: '3.8'
services:
  amber:
    network_mode: host
    environment:
      - AMBER_SOURCE=tello
      - AMBER_MAVLINK_ADDRESS=udp://:14540
      - AMBER_EDGE_WS=ws://localhost:9000
      - AMBER_OTEL_ENABLED=true
      - OTEL_EXPORTER=otlp-grpc
      - OTEL_ENDPOINT=http://localhost:4317
      - OLLAMA_HOST=http://localhost:11434
